...
...
...
	value : 33
	__name__ : storage_operation_duration_seconds_bucket
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	le : 50
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 9
[[storage_operation_duration_seconds_count]]
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 4
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 29
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 7
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 5391
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 29
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 9349
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 30
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 46
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 49
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 26
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 139
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 76238
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 46
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 49
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 22
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 406716
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 26
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 44
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 21
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 21
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 117
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 13
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 23
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 60
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 8
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 193
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 87639
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 23
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 60
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 8
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 535682
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 8
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 21
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 33
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 7
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 168
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 24
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 18
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 61
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 9
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 145
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 89071
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 18
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 61
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 7
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 451976
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 18
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 13
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 34
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 7
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 124
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 14
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 54
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 60
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 10
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 225
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 86011
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 54
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 60
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 9
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 643132
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 10
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 52
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 32
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 9
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 196
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 3
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 62
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 23
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 3717
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 62
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 13509
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 35
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 12
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 3
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 60
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 21
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 3710
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 60
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 13612
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 33
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 9
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 3
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 62
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 21
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 3702
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 62
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 13513
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 33
	__name__ : storage_operation_duration_seconds_count
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 9
[[storage_operation_duration_seconds_sum]]
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.001244863
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.011064995999999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.0018981189999999998
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 4.6093117539999975
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.07776045599999998
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 6.404098489999994
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.004686326999999999
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 0.007198973
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.009245368999999998
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 0.006055741000000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.41109437800000004
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 55.699896589999604
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.15006392500000004
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 1.9269944609999998
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 9.508131274000002
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 276.90299977399536
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 0.03939509300000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.07850734000000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.027840913
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 1.3935645920000002
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 2.4025450249999993
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.003424324
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 0.0037068550000000002
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.014464797000000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 0.001223888
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.036405877
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 52.58441380600065
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.015373458
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.36075191999999995
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 3.2495045969999996
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 341.0972050990151
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 0.010496856
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.038979999999999994
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.023126372000000003
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 0.18957535599999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 3.8912417739999996
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.003350457
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 0.0032418569999999995
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.010914970999999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 0.001168791
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.03398680100000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 58.695774493999195
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.012764662
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.08294183100000002
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 0.6022620259999999
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 279.8605538339997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 0.035372297000000004
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.027345353999999995
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.010958391999999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 0.180376345
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 1.7731262739999996
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.0023671169999999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/empty-dir
	value : 0.008258155
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.011360700999999996
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/nfs
	value : 0.0017885750000000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.044417583999999996
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 48.97559940699991
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/empty-dir
	value : 0.039019813000000014
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.012110698999999999
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 0.714132376
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 368.94856982800735
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/configmap
	value : 0.012161728
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/empty-dir
	value : 3.4155898659999995
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.010064813
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/nfs
	value : 0.6788836649999999
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 2.610714102
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.00046801899999999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.011479100999999999
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.0035467149999999993
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 1.886265058
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.009674880000000002
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 6.9543140380000095
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.009966501999999999
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 0.136359986
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.00048358600000000004
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.010559958000000003
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.003326387
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 2.084382014000004
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.011837096
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 8.193056273999971
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.022034928999999995
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 0.09272118100000001
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/configmap
	value : 0.002286948
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/host-path
	value : 0.012794058999999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : verify_controller_attached_volume
	volume_plugin : kubernetes.io/secret
	value : 0.004340072
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 2.310368500999997
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 0.011988721000000003
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 8.755300702999985
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/host-path
	value : 0.008717142999999998
	__name__ : storage_operation_duration_seconds_sum
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	operation_name : volume_unmount
	volume_plugin : kubernetes.io/secret
	value : 0.099582881
[[storage_operation_errors_total]]
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 1
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 22
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 32
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 1247
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	operation_name : volume_mount
	volume_plugin : kubernetes.io/host-path
	value : 7
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 12
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 19
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 3
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/configmap
	value : 30
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/nfs
	value : 54
	__name__ : storage_operation_errors_total
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	operation_name : volume_mount
	volume_plugin : kubernetes.io/secret
	value : 17
[[test_my_batch_job_last_success]]
	__name__ : test_my_batch_job_last_success
	job : my_batch_job2
	value : 10000
[[up]]
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : kube-state-metrics
	heritage : Tiller
	instance : 10.244.4.174:8080
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-kube-state-metrics
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode4
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.172:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode1
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.173:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode2
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.174:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode3
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.175:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode4
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.176:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode5
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.177:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode6
	release : prometheuslsk
	value : 1
	__name__ : up
	app : prometheus
	chart : prometheus-8.3.0
	component : node-exporter
	heritage : Tiller
	instance : 192.168.0.178:9100
	io_cattle_field_appId : prometheuslsk
	job : kubernetes-service-endpoints
	kubernetes_name : prometheuslsk-node-exporter
	kubernetes_namespace : prometheus
	kubernetes_node : kubenode7
	release : prometheuslsk
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	node_role_kubernetes_io_master : 
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubemaster
	node_role_kubernetes_io_master : 
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode1
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode2
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode3
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode4
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode5
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode6
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	value : 1
	__name__ : up
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes-cadvisor
	kubernetes_io_hostname : kubenode7
	value : 1
	__name__ : up
	instance : 10.244.0.10:9153
	job : kubernetes-service-endpoints
	k8s_app : kube-dns
	kubernetes_io_cluster_service : true
	kubernetes_io_name : KubeDNS
	kubernetes_name : kube-dns
	kubernetes_namespace : kube-system
	kubernetes_node : kubemaster
	value : 1
	__name__ : up
	instance : 10.244.0.11:9153
	job : kubernetes-service-endpoints
	k8s_app : kube-dns
	kubernetes_io_cluster_service : true
	kubernetes_io_name : KubeDNS
	kubernetes_name : kube-dns
	kubernetes_namespace : kube-system
	kubernetes_node : kubemaster
	value : 1
	__name__ : up
	instance : 10.244.7.7:8080
	job : kubernetes-service-endpoints
	k8s_app : kube-state-metrics
	kubernetes_name : kube-state-metrics
	kubernetes_namespace : kube-system
	kubernetes_node : kubenode6
	value : 1
	__name__ : up
	instance : 10.244.7.7:8081
	job : kubernetes-service-endpoints
	k8s_app : kube-state-metrics
	kubernetes_name : kube-state-metrics
	kubernetes_namespace : kube-system
	kubernetes_node : kubenode6
	value : 1
	__name__ : up
	instance : 192.168.0.171:6443
	job : kubernetes-apiservers
	value : 1
	__name__ : up
	instance : localhost:9090
	job : prometheus
	value : 1
	__name__ : up
	instance : prometheuslsk-pushgateway.prometheus.svc:9091
	job : prometheus-pushgateway
	value : 1
[[volume_manager_total_volumes]]
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 4
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 4
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 29
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 29
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 7
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubemaster
	job : kubernetes-nodes
	kubernetes_io_hostname : kubemaster
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 7
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 4
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 4
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/empty-dir
	state : actual_state_of_world
	value : 2
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/empty-dir
	state : desired_state_of_world
	value : 2
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 28
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 28
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/nfs
	state : actual_state_of_world
	value : 1
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/nfs
	state : desired_state_of_world
	value : 1
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 22
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode1
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode1
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 22
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 4
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 4
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/empty-dir
	state : actual_state_of_world
	value : 2
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/empty-dir
	state : desired_state_of_world
	value : 2
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/nfs
	state : actual_state_of_world
	value : 1
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/nfs
	state : desired_state_of_world
	value : 1
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 25
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode2
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode2
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 25
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 5
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 5
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/empty-dir
	state : actual_state_of_world
	value : 5
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/empty-dir
	state : desired_state_of_world
	value : 5
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 21
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode3
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode3
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 21
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/empty-dir
	state : actual_state_of_world
	value : 2
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/empty-dir
	state : desired_state_of_world
	value : 2
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 28
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 28
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 29
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode4
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode4
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 29
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 11
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode5
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode5
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 11
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 27
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 12
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode6
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode6
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 12
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	plugin_name : kubernetes.io/configmap
	state : actual_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	plugin_name : kubernetes.io/configmap
	state : desired_state_of_world
	value : 3
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	plugin_name : kubernetes.io/host-path
	state : actual_state_of_world
	value : 29
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	plugin_name : kubernetes.io/host-path
	state : desired_state_of_world
	value : 29
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	plugin_name : kubernetes.io/secret
	state : actual_state_of_world
	value : 12
	__name__ : volume_manager_total_volumes
	beta_kubernetes_io_arch : amd64
	beta_kubernetes_io_os : linux
	instance : kubenode7
	job : kubernetes-nodes
	kubernetes_io_hostname : kubenode7
	plugin_name : kubernetes.io/secret
	state : desired_state_of_world
	value : 12
